
package com.senacpi.tela;

import com.senacpi.controle.InicioControle;
import com.senacpi.modelo.Usuario;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Jake mk
 */
public class InicioTela extends javax.swing.JFrame {

    // Armazena o usuário atualmente autenticado.
    private final Usuario usuario;

    /**
     * Construtor da interface inicial da aplicação.
     * 
     * Responsável por inicializar os componentes da interface, armazenar o usuário autenticado e configurar os botões de acordo com suas permissões de acesso.
     * 
     * @param usuario O usuário autenticado que acessou o sistema.
     */
    public InicioTela(Usuario usuario) {
        initComponents();
        // receber tipo de usuário
        this.usuario = usuario;
        
        // habilitar botões de acordo com as permissões de usuário
        InicioControle iniControle = new InicioControle();
        iniControle.habilitarBotoes(usuario, btnCadastroFuncionario, btnListaFuncionario, btnCadastroPaciente, btnListaPaciente);
        lblNomeUsuario.setText(usuario.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnCadastroFuncionario = new javax.swing.JButton();
        btnListaFuncionario = new javax.swing.JButton();
        btnCadastroPaciente = new javax.swing.JButton();
        btnListaPaciente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblLogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNomeUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MovSaude - Administração de clínica");
        setPreferredSize(new java.awt.Dimension(730, 560));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnCadastroFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastroFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cadFunc.png"))); // NOI18N
        btnCadastroFuncionario.setText("Cadastro funcionário");
        btnCadastroFuncionario.setToolTipText("Cadastrar novo funcionário");
        btnCadastroFuncionario.setNextFocusableComponent(btnListaFuncionario);
        btnCadastroFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFuncionarioActionPerformed(evt);
            }
        });

        btnListaFuncionario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_listFunc.png"))); // NOI18N
        btnListaFuncionario.setText("Listagem funcionário");
        btnListaFuncionario.setToolTipText("Consultar e editar lista de funcionários");
        btnListaFuncionario.setNextFocusableComponent(btnCadastroPaciente);
        btnListaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaFuncionarioActionPerformed(evt);
            }
        });

        btnCadastroPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCadastroPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_cadPac.png"))); // NOI18N
        btnCadastroPaciente.setText("Cadastro paciente");
        btnCadastroPaciente.setToolTipText("Cadastrar novo paciente");
        btnCadastroPaciente.setNextFocusableComponent(btnListaPaciente);
        btnCadastroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPacienteActionPerformed(evt);
            }
        });

        btnListaPaciente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListaPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_listPac.png"))); // NOI18N
        btnListaPaciente.setText("Listagem paciente");
        btnListaPaciente.setToolTipText("Consultar e editar lista de pacientes");
        btnListaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaPacienteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Início");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_p.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Usuário:");

        lblNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeUsuario.setText("dev");

        lblData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblData.setText("Data");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogo)
                .addGap(85, 85, 85))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeUsuario))
                            .addComponent(lblData)))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCadastroFuncionario))
                        .addGap(27, 27, 27)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnListaPaciente)
                            .addComponent(btnCadastroPaciente))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblLogo)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListaPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListaFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblNomeUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblData)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /** Ações do botão Cadastro de Funcionário: abre a janela de cadastro. */
    private void btnCadastroFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFuncionarioActionPerformed
        CadFuncTela cadFuncTela = new CadFuncTela();
        cadFuncTela.setVisible(true);
    }//GEN-LAST:event_btnCadastroFuncionarioActionPerformed

    /** Ações do botão Listagem de Funcionários: abre a janela de listagem. */
    private void btnListaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaFuncionarioActionPerformed
        ListagemFuncTela tela = new ListagemFuncTela(usuario);
        tela.setVisible(true);
    }//GEN-LAST:event_btnListaFuncionarioActionPerformed

    /** Ações do botão Cadastro de Paciente: abre a janela de cadastro. */
    private void btnCadastroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPacienteActionPerformed
        CadPacTela pacientes = new CadPacTela();
        pacientes.setVisible(true);
    }//GEN-LAST:event_btnCadastroPacienteActionPerformed

    /** Ações do botão Listagem de Pacientes: abre a janela de listagem. */
    private void btnListaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaPacienteActionPerformed
        ListagemPaciTela listaPaci = new ListagemPaciTela(usuario);
        listaPaci.setVisible(true);
    }//GEN-LAST:event_btnListaPacienteActionPerformed

    /** Substituir label lblData pela data atual do sistema ao iniciar o form. */
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroFuncionario;
    private javax.swing.JButton btnCadastroPaciente;
    private javax.swing.JButton btnListaFuncionario;
    private javax.swing.JButton btnListaPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblLogo;
    public static javax.swing.JLabel lblNomeUsuario;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
