
package com.senacpi.tela;

import com.senacpi.controle.LoginControle;
import com.senacpi.dao.Criptografia;
import com.senacpi.dao.JpaUtil;
import com.senacpi.dao.UsuarioDao;
import com.senacpi.modelo.Usuario;
import com.senacpi.tela.InicioTela;
import javax.swing.JOptionPane;

/**
 *
 * @author Jake mk
 */
public class LoginTela extends javax.swing.JFrame {

    /**
     * Cria novo formulário LoginTela.
     * 
     * Inicializa os componentes da interface.
     * Configura ícone informando se há conexão com banco de dados.
     */
    public LoginTela() {
        initComponents();
        mostrarIconeBD();
    }
    
    private void mostrarIconeBD() {
        // ícone indicando se o entityManager não consiga encontrar o banco de dados
        if (JpaUtil.getEntityManager() == null) {
            lblBd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_bd_falha.png")));
        } else {
            lblBd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_bd_exito.png")));
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlLogo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblMovSaude = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        btnEntrar = new javax.swing.JButton();
        lblLogin = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        lblBd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login MovSaude");
        setPreferredSize(new java.awt.Dimension(700, 550));
        setResizable(false);

        pnlPrincipal.setPreferredSize(new java.awt.Dimension(400, 312));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        lblMovSaude.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMovSaude.setText("Movimento Saúde Mental");

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addGroup(pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblMovSaude))
                    .addGroup(pnlLogoLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel2)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMovSaude)
                .addContainerGap())
        );

        lblUsuario.setText("Usuário*");

        lblSenha.setText("Senha*");

        txtUsuario.setText("jenifer");
        txtUsuario.setToolTipText("Digite o usuário (primeiro nome em letras minúsculas)");
        txtUsuario.setNextFocusableComponent(txtSenha);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(152, 110, 172));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setToolTipText("Botão para entrar no sistema");
        btnEntrar.setNextFocusableComponent(txtUsuario);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblLogin.setText("Login");

        txtSenha.setText("2386");
        txtSenha.setToolTipText("Digite a senha");
        txtSenha.setNextFocusableComponent(btnEntrar);

        lblBd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icon_bd_falha.png"))); // NOI18N

        jLabel1.setText("jenifer 2386 | stephany 4846 | cris 1830");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSenha)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(lblLogin))
                    .addComponent(txtSenha))
                .addGap(221, 221, 221))
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblBd)
                        .addGap(153, 153, 153)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jLabel1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addComponent(lblSenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblBd))
                    .addComponent(jLabel1))
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        LoginControle lcontrole = new LoginControle();

        String login = txtUsuario.getText();
        String senhaTexto = new String(txtSenha.getPassword());
        String senha = Criptografia.getMD5(senhaTexto);
        
        
        if (!lcontrole.formatosInvalidos(login, senhaTexto) && !lcontrole.camposVazios(login, senhaTexto)) {
            Usuario usuario = new Usuario();
            usuario.setLogin(login);
            usuario.setSenha(senha);
            
            // validação: retorna null se não corresponder com o informado
            Usuario usuarioValidado = UsuarioDao.validarUsuario(usuario);

            // Abre a tela inicial do programa com as permissões do tipo de usuário
            abrirTelaPorTipoUsuario(usuarioValidado);
        } else {
            JOptionPane.showMessageDialog(null, "Usuário inválido. Verifique os campos preenchidos.");
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    // TODO: refatorar com else caso o usuário seja nulo
    private void abrirTelaPorTipoUsuario(Usuario usuario) {
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "Usuário não encontrado.");
            return;
        }

        String perfil = usuario.getPerfil();
       
        if(perfil == null || perfil.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Perfil de usuário não definido.");
            return;
        }
       
        switch (usuario.getPerfil().toLowerCase()) {
            case "admin":
            case "psi":
            case "fin": // se o usuario for do tipo financeiro
                abrirTela(usuario);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Tipo de usuário descohecido.");
                break;
        }
    } 
    
    /**
     * Método para abrir a tela de início.
     * Abre a tela de início de de acordo com o tipo de usuário logado. 
     * Fecha a tela atual de login.
     * @param usuario Objeto do usuário autenticado, utilizado para aplicar permissões e regras de acesso. 
     */
    private void abrirTela(Usuario usuario) {
        InicioTela tela = new InicioTela(usuario);
        tela.setVisible(true);
        this.dispose();
    }

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Registra o shutdown hook
        Runtime.getRuntime().addShutdownHook(new Thread(()-> {
            System.out.println("Encerrando aplicação... liberando recursos.");
            JpaUtil.closeFactory();
        }));
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBd;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMovSaude;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

   
}
